import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { client } from "../utils/client";

type Data = {
  friends: Record<string, string>[];
};

const QUERY = `query {
  friend {
    name
  }
}`;

export const getServerSideProps: GetServerSideProps<Data> = async (context) => {
  return client
    .query(QUERY, {})
    .toPromise()
    .then((d) => ({
      props: { friends: d.data.friend },
    }));
};

export default function Home<NextPage>({
  friends,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {friends.map((friend) => (
          <h2 key={friend.name}>{friend.name}</h2>
        ))}
      </main>
    </div>
  );
}
